[build]
  command = "npm run build"
  publish = "public"

[build.environment]
  PHP_VERSION = "8.3"
  NODE_VERSION = "20"

[[redirects]]
  from = "/build/*"
  to = "/build/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200
